# This is a basic workflow to help you get started with Actions

name: POC-WINFLEX-25

run-name: Started by @${{ github.actor }} with commit ${{ github.sha }} on target branch ${{ github.base_ref }} branch

# Controls when the workflow will run
on:
  # Triggers the workflow for pull requests:
  # - with target branch in the list 'branches'
  # - only for actions on pull requests listed in the list 'types'
  pull_request:
    branches: [ "main", "development", "feature/*" ]
    types: ["created", "reopened", "synchronize"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The next list starts a workflow job called 'POC-WINFLEX-2504-Job'
  WINFLEX-2504-Job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hola, Winflex-Mate. Doing an amazing and super important work here. Do not disturb me!