# This is a basic workflow to help you get started with Actions

name: STAGE_TO_PREPROD

run-name: Staging triggered by @${{ github.actor }} with commit ${{ github.sha }} on target branch ${{ github.base_ref }} branch

# Controls when the workflow will run
on:
  # Triggers the workflow for pull requests:
  # - with target branch in the list 'branches'
  # - only for actions on pull requests listed in the list 'types'
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The next list starts a workflow job called 'POC-WINFLEX-2504-Job'
  WINFLEX-2504-Job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "🔎 The commit sha is ${{ github.sha }}."

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Staging this magnificent application to PREPROD
        run: echo Doing this and that to stage to PREPROD


